# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dizain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 723)
        MainWindow.setStyleSheet("background-color: rgb(92, 130, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 601, 261))
        self.frame.setStyleSheet("background-color: rgb(255, 34, 148);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 20, 221, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(16, 28, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 441, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Strelka.jpg"))
        self.label_2.setObjectName("label_2")
        self.input_rrence = QtWidgets.QLineEdit(self.centralwidget)
        self.input_rrence.setGeometry(QtCore.QRect(120, 320, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.input_rrence.setFont(font)
        self.input_rrence.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white")
        self.input_rrence.setText("")
        self.input_rrence.setAlignment(QtCore.Qt.AlignCenter)
        self.input_rrence.setObjectName("input_rrence")
        self.inpunr_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.inpunr_amount.setGeometry(QtCore.QRect(120, 400, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.inpunr_amount.setFont(font)
        self.inpunr_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white")
        self.inpunr_amount.setText("")
        self.inpunr_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.inpunr_amount.setObjectName("inpunr_amount")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(120, 480, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white")
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(120, 560, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white")
        self.input_amount.setText("")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 650, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #fb5b5b;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244\n"
"}\n"
"    ")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертер Валют"))
        self.pushButton.setText(_translate("MainWindow", "Конвертируем валюту"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
